//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ConvertToNC.rc 使用
//
#define ID_BTN_DEFAULT                  3
#define IDR_MENU_ADDORDEL               4
#define IDS_PROJNAME                    100
#define IDC_LIST_BOX                    100
#define IDD_SYSTEM_SETTING_DLG          101
#define IDC_E_PROP_HELP_STR             101
#define IDS_REVISION                    101
#define IDS_PART_LIST                   102
#define IDD_FILTER_LAYER_DLG            104
#define IDD_INPUT_MK_RECT_DLG           105
#define IDB_IL_PROJECT                  105
#define IDD_PART_LIST_DLG               107
#define IDI_LEFT_ROTATE                 111
#define IDI_RIGHT_ROTATE                113
#define IDC_TAB_GROUP                   114
#define IDC_LIST1                       115
#define IDC_PART_LIST                   115
#define IDC_LIST_CTRL                   116
#define IDC_E_RECT_L                    117
#define IDB_LEFT_ROTATE                 117
#define IDC_E_RECT_W                    118
#define IDB_MIRROR                      118
#define IDC_E_TEXT_H                    119
#define IDB_RIGHT_ROTATE                119
#define IDB_BITMAP1                     120
#define IDB_MOVE                        120
#define IDB_MOVE_MK                     121
#define IDC_BTN_SEND_TO_PPE             122
#define IDC_BTN_EXPORT_DXF              123
#define IDC_BTN_CLOCKWISE_ROTATION      124
#define IDC_BTN_MIRROR                  125
#define IDD_EXPLODE_TXT_DLG             125
#define IDC_BTN_ANTICLOCKWISE_ROTATION  126
#define IDC_BTN_MOVE                    127
#define IDC_BTN_MOVE_MK_RECT            128
#define IDD_SEL_COLOR_DLG               128
#define IDC_CHECK1                      129
#define IDC_CHK_EDIT_MK                 129
#define IDC_CHK_GRADE                   131
#define IDC_LIST_SYSTEM_SETTING_DLG     132
#define IDC_CHK_MAT_H                   132
#define IDC_E_SEARCH_TEXT               133
#define IDC_BTN_SEARCH                  134
#define IDC_TREE_CTRL                   135
#define IDD_REVISION_DLG                136
#define IDC_BTN_PDF                     136
#define IDC_BTN_PNG                     137
#define IDC_E_LEN_ERR                   138
#define IDR_ITEM_CMD_POPUP              140
#define IDC_E_NOTE                      140
#define IDC_TREE_CONTRL                 141
#define IDC_E_FILE_NAME                 142
#define IDC_E_NUM                       143
#define IDC_BTN_EXTRACT                 144
#define IDC_CMB_EDGE_CLR                145
#define IDC_CMB_M12_CLR                 146
#define IDC_CMB_M16_CLR                 147
#define IDC_CMB_M20_CLR                 148
#define IDC_CMB_M24_CLR                 149
#define IDC_CMB_OTHER_CLR               150
#define IDD_OPTIMAL_SORT_DLG            288
#define IDC_LIST_REPORT                 1025
#define IDC_JG_LIST                     6000
#define IDC_CHE_JG                      6001
#define IDC_CHE_YG                      6002
#define IDC_CHE_TUBE                    6003
#define IDC_CHE_FLAT                    6004
#define IDC_CHE_JIG                     6005
#define IDC_CHE_GGS                     6006
#define IDC_CHE_Q345                    6007
#define IDC_CHE_Q235                    6008
#define IDC_CHE_Q390                    6009
#define IDC_CHE_Q420                    6010
#define IDC_CHE_Q460                    6011
#define IDC_E_WIDTH                     6012
#define IDC_E_THICK                     6013
#define IDC_CHE_CUT_ANGLE               6014
#define IDC_CHE_PLATE                   6015
#define IDC_CHE_Q355                    6016
#define IDC_CHE_KAIHE                   6017
#define IDC_CHE_PUSH_FLAT               6018
#define IDC_CHE_CUT_ROOT                6019
#define IDC_CHE_CUT_BER                 6020
#define IDC_CHE_BEND                    6021
#define IDC_CHE_COMMON_ANGLE            6022
#define ID_MODIFY_TMA_FILE              32766
#define ID_MARK_FILTER                  32767
#define ID_CANCEL_FILTER                32768
#define ID_NEW_ITEM                     32769
#define ID_LOAD_PROJECT                 32770
#define ID_IMPORT_TMA_FILE              32771
#define ID_IMPORT_ERP_FILE              32772
#define ID_MENU_PNCSYS_ADD              32772
#define ID_IMPORT_ANGLE_DWG             32773
#define ID_MENU_PNCSYS_DEL              32773
#define ID_IMPORT_PLATE_DWG             32774
#define ID_PROJECT_PROPERTY             32775
#define ID_IMPORT_BOM_FILE              32776
#define ID_COMPARE_DATA                 32777
#define ID_MENU_BOLT_ADD                32777
#define ID_EXPORT_COMPARE_RESULT        32778
#define ID_MENU_BOLT_DEL                32778
#define ID_REFRESH_PART_NUM             32779
#define ID_EXPORT_PROJECT               32780
#define ID_REFRESH_WEIGHT               32781
#define ID_REVISE_TEH_PLATE             32782
#define ID_RETRIEVED_ANGLES             32783
#define ID_RETRIEVED_PLATES             32784
#define ID_MODIFY_ERP_FILE              32785
#define ID_DELETE_ITEM                  32786
#define ID_SAVE_ITEM                    32787
#define ID_IMPORT_ITEM                  32788
#define ID_EXPLODE_ITEM                 32789
#define ID_CLOSE_ITEM                   32790
#define ID_REFRESH_SINGLE_NUM           32791
#define ID_BATCH_PRINT_PART             32792

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         146
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
