#ifndef __TOOLBAR_IMAGE_H_
#define __TOOLBAR_IMAGE_H_

enum PROJECT_IMAGE{
	PRJ_IMG_ROOT,
	PRJ_IMG_PARTGROUP,
	PRJ_IMG_VIEWSET,
	PRJ_IMG_LAYERVIEW,
	PRJ_IMG_CALMODULE,
	PRJ_IMG_MODULECASE,
	PRJ_IMG_TOWERBODY,
	PRJ_IMG_TOWERLEG,
	PRJ_IMG_TOWERACTIVELEG,
	PRJ_IMG_WIRELAYOUTSET,
	PRJ_IMG_WIRELAYOUT,
	PRJ_IMG_WIRELOADSET,
	PRJ_IMG_WIRELOAD,
	PRJ_IMG_STATUSSET,
	PRJ_IMG_STATUS,
	PRJ_IMG_POINTLOAD,
	PRJ_IMG_WEIGHTLOAD,
	PRJ_IMG_WINDLOAD,
	PRJ_IMG_WINDLOADPARA,
	PRJ_IMG_EARTHQUAKE,
	PRJ_IMG_BOUDARY,
	PRJ_IMG_MATERIAL,
	PRJ_IMG_SWAGE,			//型铁
	PRJ_IMG_MATERIALITEM,
	PRJ_IMG_ANGLE,
	PRJ_IMG_COMPOSITE_PART,	//组合件
	PRJ_IMG_TUBE,
	PRJ_IMG_SLOT,			//槽钢
	PRJ_IMG_FLAT,			//扁钢
	PRJ_IMG_GUYS,
	PRJ_IMG_POINTLOADITEM,
	PRJ_IMG_WEIGHTLOADITEM,
	PRJ_IMG_BOUNDARYNODE,
	PRJ_IMG_PARA,
	PRJ_IMG_WINDSEG,
	PRJ_IMG_MAT_ELASTICITY,
	PRJ_IMG_MAT_INTENSITY,
	PRJ_IMG_MAT_BOLT,
	PRJ_IMG_DATUM_PRIMITIVE_ELEMENT_GROUP,
	PRJ_IMG_DATUM_POINT_GROUP,
	PRJ_IMG_DATUM_LINE_GROUP,
	PRJ_IMG_DATUM_PLANE_GROUP,
	PRJ_IMG_DATUM_POINT,
	PRJ_IMG_DATUM_LINE,
	PRJ_IMG_DATUM_PLANE,
	PRJ_IMG_ATTACH_WINDLOAD,
	PRJ_IMG_FL,				//法兰	
	PRJ_IMG_C_INSERTPLATE,	//槽型插板
	PRJ_IMG_U_INSERTPLATE,	//U型插板
	PRJ_IMG_X_INSERTPLATE,	//十字型插板
	PRJ_IMG_X_EDIT_STATE,	//编辑状态
	PRJ_IMG_ARC_LIFT_GROUP,	//圆弧预拱项集合
	PRJ_IMG_ARC_LIFT_CASE,	//圆弧预拱项
	PRJ_IMG_IMPORT_BLOCK_CASE,			//非内嵌部件集合
	PRJ_IMG_UNEXPLODED_BLOCKREF_CASE,	//非炸开部件引用
	PRJ_IMG_EMBED_BLOCK_CASE,			//内嵌部件集合
	PRJ_IMG_EXPLODED_BLOCKREF_CASE,		//炸开部件引用
	PRJ_IMG_ACS,			//装配位置
	PRJ_IMG_FILEGROUP,		//文件组
	PRJ_IMG_FILE,			//文件
	PRJ_IMG_SEGGROUP,		//分段组
	PRJ_IMG_NO_ATTACH_FILE,	//无关联文件
	PRJ_IMG_FOOT,			//塔脚
};
#endif